from .animal import Animal
from .alligator import Alligator
from .camel import Camel
from .donkey import Donkey
from .emu import Emu
from .flamingo import Flamingo
from .frog import Frog
from .goat import Goat
from .goldfish import Goldfish
from .hippopotamus import Hippopotamus
from .lizard import Lizard
from .llama import Llama
from .mallard import Mallard
from .snake import Snake
from .tarantula import Tarantula
from .turtle import Turtle
from .goose import Goose